### ISSUE TITLE
Never create the service for winlogbeat.

### ISSUE THREAD

**Issue by zdhamilton** [logzio/logz-docs#368]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [x] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 

#### Describe the issue

Given what we have right now, we don't have people run "install-service-winlogbeat.ps1" which comes with winlogbeat when you down load it. Since we're telling people to run it as a service from the command prompt, we should have them create the executable as a service first. If they don't, "Restart-Service winlogbeat" or "Start-Service winlogbeat" wont work. 

An additional caveat. On some machines, it wont allow you to run "install-service-winlogbeat.ps1" since it is unsigned. The command: "PowerShell.exe -ExecutionPolicy UnRestricted -File .\install-service-winlogbeat.ps1" has helped me bypass this in the past. 

#### Recommended fix

I would just add those as gotcha's or potential steps in the docs.

**Comment by imnotashrimp** [comment]
My gut here is to remove the command and replace it with what we do in Filebeat - which is 'Start or restart Filebeat'. We do this because users were running into trouble when I supplied a command because no one command applies in all situations.

I think we've got a little bit of the same thing going on here - would it make sense just to change it to 'Start or restart Winlogbeat for the changes to take effect.' @zdhamilton ?

**Comment by zdhamilton** [comment]
Yes I think that makes sense. 

Would something like, "If you're starting Winlogbeat, and haven't configured it as a service yet, see this documentation <here> for how to do so"

**Comment by nico-shishkin** [comment]
https://github.com/logzio/logz-docs/pull/2068
